 - name: Demo on using shell module
   hosts: all
   tasks:
    - name: Demo on using shell module
      ansible.builtin.shell: uptime
      register: OUT
     - name: Printing the output variable
      ansible.builtin.debug:
        msg: "{{OUT}}"