- name: Demo on using conditions
  hosts: all 
  tasks:
    - name: This is a frontend task
      ansible.builtin.debug:
       msg: Installing frontend
    - name: Starting frontend
      ansible.builtin.debug:
       msg: strating frontend
    - name: This is a user task
      ansible.builtin.debug:
       msg: Installing user
    - name: Starting user
      ansible.builtin.debug:
       msg: strating user
        - name: This is a cart task
      ansible.builtin.debug:
       msg: Installing cart
    - name: Starting cart
      ansible.builtin.debug:
       msg: strating cart