- name: Demo on using conditions
  hosts: all 
  tasks:
    - name: This is a frontend task
      ansible.builtin.debug:
       msg: Installing frontend
      tags: fronend
    - name: Starting frontend
      ansible.builtin.debug:
       msg: strating frontend
      tags: frontend
    - name: This is a user task
      ansible.builtin.debug:
       msg: Installing user
      tags: user
    - name: Starting user
      ansible.builtin.debug:
       msg: strating user
      tags: user
    - name: This is a cart task
      ansible.builtin.debug:
       msg: Installing cart
      tags: cart
    - name: Starting cart
      ansible.builtin.debug:
       msg: strating cart
      tags: cart